version: "3"
services:
  webapp:
    build:
      context: ./app
    ports:
      - "8080:8080"
  nginx:
    image: nginx:stable-perl
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - webapp
      - mysql
  mysql:
    image: mysql:8.0
    ports:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=A?2I&4*dMXc8
      - ENV MYSQL_DATABASE=java_db
      - ENV MYSQL_USER=admin
      - ENV MYSQL_PASSWORD=c49WE6$#X}Jv